project:
  type: website

website:
  title: "Glittr.org statistics"
  navbar:
    background: "#8338ec"
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/sib-swiss/glittr-stats/
        aria-label: GitHub

format:
  html:
    theme: 
      - default
      - custom.scss
    toc: true
    code-link: true
    header-includes: |
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
      
execute:
  freeze: auto



