project:
  type: website

website:
  title: "Glittr.org statistics"
  favicon: "assets/icon/icon-stroke.svg"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/sib-swiss/glittr-stats/
        aria-label: GitHub
  sidebar:
    logo: "assets/logo/logo-with-domain.svg"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    highlight-style: ayu
    toc: true
    code-link: true
    header-includes: |
      <link rel="stylesheet" href="https://fonts.bunny.net/css?family=source-sans-3:200,400,600,700&display=swap">

      
execute:
  freeze: auto



