project:
  type: website

website:
  title: "Glittr.org statistics"
  navbar:
    background: "#8338ec"
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/sib-swiss/glittr-stats/
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto



